version: "3.9"

services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g

  model_api:
    image: python:3.11-slim
    container_name: model-api
    working_dir: /app
    volumes:
      - ./model-api:/app
    command: >
      sh -c "pip install -r requirements.txt && python build.py"
    ports:
      - "8000:8000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m

  streamlit:
    image: python:3.11-slim
    container_name: streamlit-app
    working_dir: /app
    volumes:
      - ./streamlit:/app
    command: >
      sh -c "pip install -r requirements.txt && streamlit run app.py --server.port=8501 --server.enableCORS=false"
    ports:
      - "8501:8501"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m

volumes:
  jenkins_home:
