version: "3.9"

services:

  streamlit:
    image: python:3.11-slim
    container_name: streamlit
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      sh -c "pip install -r requirements.txt && streamlit run StreamlitApp.py --server.port=8501 --server.enableCORS=false"
    ports:
      - "80:8501"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
  
  model_server:
    image: python:3.11-slim
    container_name: model_server
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      sh -c "pip install -r requirements.txt && fastapi run ModelServer.py --port 80 "
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
  
  data_server:
    image: python:3.11-slim
    container_name: data_server
    working_dir: /app
    volumes:
      - ./:/app
    command: >
       sh -c "pip install -r requirements.txt && fastapi run DataServer.py --port 80 "
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m


